/*
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl1.ui;

import casinoDSL.ui.internal.CasinoDSLActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CasinoDSLActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CasinoDSLActivator activator = CasinoDSLActivator.getInstance();
		return activator != null ? activator.getInjector(CasinoDSLActivator.ORG_XTEXT_EXAMPLE_MYDSL1_MYDSL) : null;
	}

}
