/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Css</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getCss()
 * @model
 * @generated
 */
public interface Css extends File
{
} // Css
