/*
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl1.ui.tests;

import casinoDSL.ui.internal.CasinoDSLActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CasinoDSLActivator.getInstance().getInjector("org.xtext.example.mydsl1.MyDsl");
	}

}
